image:
  repository: 704892510569.dkr.ecr.us-east-1.amazonaws.com/varta-svc-agent
  tag: "0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 8090
  type: ClusterIP

env:
  USE_MOCKS: "true"
  LOG_LEVEL: DEBUG
  CORE_API_BASE: http://localhost:8080/api/v1
  MODEL_NAME: openai:gpt-5
  EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
  MAX_TOKENS: 3000
  TEMPERATURE: 0.3

envFrom:
  - secretRef:
      name: agent-secrets

resources: {}      # e.g. set later:
#  requests:
#    cpu: 100m
#    memory: 128Mi
#  limits:
#    cpu: 500m
#    memory: 512Mi
